# -*- coding: utf-8 -*-
"""test_run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBSXyzsmniw2BJ_rX_hECF3uGWL9DtXL
"""

# test_run.py

import csv
from deliverable21 import URLValidator

# Instantiate the URLValidator
validator = URLValidator()

# Define a list of 10 sample rows with user prompts, URLs, and manual custom ratings.
data = [
    {
        "user_prompt": "I have just been on an international flight",
        "url_to_check": "https://www.mayoclinic.org/healthy-lifestyle/infant-and-toddler-health/expert-answers/air-travel-with-infant/faq-20058539",
        "custom_rating": 4
    },
    {
        "user_prompt": "Can I travel with my newborn safely?",
        "url_to_check": "https://www.webmd.com/parenting/features/traveling-with-newborns",
        "custom_rating": 5
    },
    {
        "user_prompt": "What are the vaccination requirements for traveling?",
        "url_to_check": "https://www.cdc.gov/travel/page/vaccinations",
        "custom_rating": 3
    },
    {
        "user_prompt": "How do I maintain a healthy diet on a long flight?",
        "url_to_check": "https://www.healthline.com/nutrition/healthy-airplane-snacks",
        "custom_rating": 4
    },
    {
        "user_prompt": "Is it safe to use public transport during a pandemic?",
        "url_to_check": "https://www.who.int/news-room/questions-and-answers/item/coronavirus-disease-covid-19-public-transport",
        "custom_rating": 3
    },
    {
        "user_prompt": "What are the latest travel restrictions?",
        "url_to_check": "https://www.state.gov/visas/",
        "custom_rating": 4
    },
    {
        "user_prompt": "Can I bring my pet on an international flight?",
        "url_to_check": "https://www.americanpetproducts.org/press_room/pet_travel",
        "custom_rating": 4
    },
    {
        "user_prompt": "What are the top destinations for families?",
        "url_to_check": "https://www.lonelyplanet.com/best-in-travel",
        "custom_rating": 5
    },
    {
        "user_prompt": "How do I pack efficiently for a trip?",
        "url_to_check": "https://www.travelandleisure.com/travel-tips/packing-tips",
        "custom_rating": 3
    },
    {
        "user_prompt": "Is travel insurance worth it?",
        "url_to_check": "https://www.forbes.com/advisor/travel-insurance/",
        "custom_rating": 4
    }
]

# Process each row to compute the function rating using the URLValidator
results = []
for item in data:
    user_prompt = item["user_prompt"]
    url = item["url_to_check"]
    custom_rating = item["custom_rating"]

    # Compute the URL validity rating
    result = validator.rate_url_validity(user_prompt, url)
    # Extract the function rating (star score)
    func_rating = result["stars"]["score"]

    results.append({
        "user_prompt": user_prompt,
        "url_to_check": url,
        "func_rating": func_rating,
        "custom_rating": custom_rating
    })

# Write the results to a CSV file with the specified columns
csv_filename = "url_ratings.csv"
with open(csv_filename, "w", newline="", encoding="utf-8") as csvfile:
    fieldnames = ["user_prompt", "url_to_check", "func_rating", "custom_rating"]
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for row in results:
        writer.writerow(row)

print(f"CSV file '{csv_filename}' has been created with the URL ratings.")